DbtBigquery:
  outputs:
    dev:
      dataset: dbt_bigquery
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\ericm\.dbt\dbt-bigquery.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-bigquery-422616
      threads: 1
      type: bigquery
  target: dev